version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
    - MYSQL_ROOT_PASSWORD=12345
      #- MYSQL_ROOT_HOST:'%'  
    - MYSQL_DATABASE=springbootdb
      #- MYSQL_USER=root
      #- MYSQL_PASSWORD=12345
    ports:
    - 3306:3306

  myapp-main:
    build: .
    #links:
    #- myapp-mysql         
     
    #restart: on-failure
    depends_on:
    - myapp-mysql
    ports:
    - 8080:8080
      #environment:
      #- DATABASE_HOST=myapp-mysql
      #- DATABASE_USER=root
      #- DATABASE_PASSWORD=12345
      #- DATABASE_NAME=springbootdb
      #- DATABASE_PORT=3306
